### ISSUE TITLE
`TextBone` respects deprecated `validHtml`, but should use `valid_html`

### ISSUE THREAD

**Issue by phorward** [viur-framework/vi-vue-utils#10]
When using the viur-core without backward compatiblity mode, any TextBone is rendered as a <textarea>, but <ckeditor> should be used. This is, because the deprecated `validHtml` setting is used, but `valid_html` is the correct setting.

This is the place https://github.com/viur-framework/vi-vue-utils/blob/main/packages/viur-vue-utils/bones/edit/default/textBone.vue#L4 which causes this invalid distinction.

**Comment by KadirBalku** [comment]
Issue adressed in #11 - needs further testing!
