### ISSUE TITLE
`SelectBone` should be able to handle key-value-object (new-style) in its values

### ISSUE THREAD

**Issue by phorward** [viur-framework/vi-vue-utils#12]
A SelectBone's structure is currently described like this:
```json
"structure": {
  ...
  "active": {
    "descr": "Aktiv",
    "type": "select",
    "values": [
      ["0", "Nein"],
      ["1", "Ja"]
    ]
  }
  ...
}
```
but viur-framework/viur-core#1203 enforces to use the dict-attempt, which is more straightforward and easier to handle, so the structure will look like this
```json
"structure": {
  ...
  "active": {
    "descr": "Aktiv",
    "type": "select",
    "values": {
      "0": "Nein",
      "1": "Ja"
    }
  }
  ...
}
```

Currently sending latter one to vi-admin, the result is this:
![shot-2024-06-28_12-45-44](https://github.com/viur-framework/vi-vue-utils/assets/16870072/77b2d8cc-b471-4a76-a0e1-ce7ed7ed346e)

Both definitions, the old-style list-tuple and new-style dict should be supported in [selectBone.vue](https://github.com/viur-framework/vi-vue-utils/blob/main/packages/viur-vue-utils/bones/edit/default/selectBone.vue)

**Comment by phorward** [comment]
The new-style layout can now be activated by removing `"bone.select.structure.values.keytuple"` from `conf.compatibility` introduced with https://github.com/viur-framework/viur-core/pull/1203/commits/cfa114631dad0b88491250ed438a5241ef95b513

**Comment by KadirBalku** [comment]
Issue adressed in v1.4.10
